### ISSUE TITLE
Change Terms "Peg" to "Import" and "Unpeg" to "Export" in the DEX UI and DEX UI docs

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/peggy#51] opened 2021-03-29 05:41 UTC
URL: https://testnet.sifchain.finance/#/peg -> https://testnet.sifchain.finance/#/import-export
Peg Icon label: "Peg" -> "Import/Export"

External Tokens Window: "Peg" -> "Import"
Peg Asset Window: "Peg Asset" -> "Import Asset", "Peg" button label -> "Import" button label
Peg Token Confirmation Window: "Peg token to Sifchain" -> "Import token to Sifchain", "Peg Amount"-> "Import Amount", "Confirm Peg" -> "Confirm Import" 
Waiting for confirmation/Transaction submitted/Transaction Failed window: "Pegging 0.001 eth" -> "Importing 0.001 eth"

Sifchain Native Window: "Unpeg" -> "Export"
Unpeg Asset Window: "Unpeg Asset" -> "Export Asset", "Unpeg" button label -> "Export" button label
Unpeg Token Confirmation Window: "Unpeg token from Sifchain" -> "Export token from Sifchain", "Unpeg Amount"-> "Export Amount", "Confirm Unpeg" -> "Confirm Export" 
Waiting for confirmation/Transaction submitted/Transaction Failed window: "Unpegging 0.001 eth" -> "Exporting 0.001 eth"

Transaction Status Notifications: Pegging/Pegged -> Importing/Imported, Unpegging/Unpegged -> Exporting/Exported

Not sure if this list is exhaustive. Please grep the codebase for any peg/unpeg references. This should be launched at the same time as the changes to the documentation https://docs.sifchain.finance/resources/sifchain-dex-ui to avoid confusion.

**Comment by 59023g** [comment] 2021-05-05 03:24
@ryardley How we looking on this?

**Comment by sifmoon** [comment] 2021-05-06 18:53
@ryardley any updates on this ticket?

**Comment by thomasdavis** [comment] 2021-05-11 13:37
I had a play around with this ticket today. 

We currently have 673 words that contain peg in the `ui` codebase. 

I can swap out all the visual elements, which shouldn't cause too many pains. 

But we will have a lot of `methods` still throughout the codebase which still contain the peg/unpeg semantics. 

Which could be a technical debt nightmare as developers will have to cognitively switch between export/import/peg/unpeg. 

To switch out all references to peg visually/internally could be easy-ish™, but it would be hard to not promise that there wouldn't be regressions. 

So I am sort of asking for opinions on whether we should just switch the terminology in user facing situations and leave our internals as peg/unpeg. Or go for the full refactor and get rid of the idea of peg/unpeg. 

===

On a separate note, I know a lot of people have put a lot of time in already coming to this decision but I will just throw my 2cents in that I am not convinced that it is necessary; 

- There are barely any competitors on the market that have the idea of pegging assets to another chain (sifchain). It is understandable that a lot of users don't have the background to understand peg/unpeg. From a purely financial perspective, peg/unpeg fits perfectly, and a) we could educate our users about this b) the community as a whole might likely understand peg/unpeg as multi-chains come more common place 
- import/export is already quite well grounded in the crypto world; 
   - import/export keys 
   - import/export reports 
   (I don't think throwing a button with "Export" on it in places would be that understandable. Unless we always went with something like "Export Funds") 
   
Should have written these notes earlier in the discussion, will go with it but some commentary on the first point would be awesome, thanks!

**Comment by 59023g** [comment] 2021-05-11 16:32
I'm fine with changes being DOM only. I don't think the translation is too much cognitive overhead for devs. That said, our tests would hopefully pick up any regressions which may arise from a full swap out of all `peg` references. @ryardley ?

As far as the necessity of this, it's a done deal.

**Comment by sifmoon** [comment] 2021-05-11 20:59
I'll let @pandaring2you comment on here around reasoning in switching to import/export and if this is something we want to revisit.

I will say though, in my opinion, I think eventually we will be getting away from doing any type of import/peg, export/unpeg all together. And the only time a user will need to 'transfer' funds would be to get eROWAN into sifchain as ROWAN. 

So I am okay with just changing the FE for this and leaving the BE as is as we will likely abandon this type of user flow from the FE all-together in the far away future

**Comment by 59023g** [comment] 2021-05-11 21:24
This is a good direction. And lends itself to leaving the view/core methods as is. Because, even if the transaction type is abstracted for end user (ie "everything is a swap"), under the hood, we'll still need to do the relevant transaction (ie peg/import, swap, etc).

ADDENDUM: However, if the whole org will use "import/export" language going forward, I think we should too.

**Comment by ryardley** [comment] 2021-05-11 22:45
Definitely should not change any underlying code terms even in the frontend. Peg and unpeg are industry terms that have specific meanings. I would think of this as a copy change only type operation

**Comment by 59023g** [comment] 2021-05-11 22:53
> Peg and unpeg are industry terms that have specific meanings.

Are they? They're our terms and we're changing them to import/export.

**Comment by ryardley** [comment] 2021-05-11 23:17
People talk about peg zones with cosmos blockchains all the time https://blog.cosmos.network/the-internet-of-blockchains-how-cosmos-does-interoperability-starting-with-the-ethereum-peg-zone-8744d4d2bc3f

**Comment by 59023g** [comment] 2021-05-11 23:36
Yea, then let's leave our underlying code as is and just change the DOM. Will be quicker too.  I asked our Peggy guys, James said:
>As we're writing peggy2 code we should think about that, but we're not planning on doing anything before then AFAIK
Most of the cli stuff uses lock/burn terminology not peg and unpeg
The design docs we have try to use export/import

**Comment by pandaring2you** [comment] 2021-05-12 18:46
Agreed that it's not worth the work to refactor the backend. just changing the front end seems fine. the import/export terms were requested by @jkbrooks, so not sure how high of a priority this is. from a non-Cosmos crypto user perspective, import/export seems like a more intuitive abstraction (they don't have to think about what a peg means, just that they're bringing their token onto sifchain). also, the "unpeg" term is incorrect for sifchain native assets because they were never pegged to sifchain to begin with - could lead to confusion.

**Comment by sifmoon** [comment] 2021-05-24 23:11
Looks good. I still need to update the docs here.  Moving along to be merged into TestNet

**Closed as completed** 2021-06-18 19:35 UTC
Labels: Front End Team
