### ISSUE TITLE
Define logging best practices in our coding standards

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/peggy#50] opened 2021-03-24 22:27 UTC
Task from structured logging meeting 3/23

What is the right/important content to go into various levels (comprehensive, but no private data)?
How do you implement logging?
When to log?

**Comment by khdegraaf** [comment] 2021-03-24 23:23
Hey, this is a dupe of https://github.com/Sifchain/issues/issues/201.  If you think anything is missing, feel free to add some comments there.

**Closed as completed by khdegraaf** 2021-03-24 23:23 UTC
