### ISSUE TITLE
Make sure cosmosDenom is safe with JimmyTokens

### ISSUE THREAD

**Issue by zikarium** [Sifchain/peggy#131] opened 2021-11-18 15:41 UTC

**Comment by pandaring2you** [comment] 2021-12-02 23:22
Test case: If someone tries to game us with a chameleon token (data changes randomly)

**Comment by pandaring2you** [comment] 2021-12-07 17:06
(not critical as we have other tests that cover this)

**Comment by pandaring2you** [comment] 2022-03-10 23:48
this is a duplicate of the troll token test

**Closed as completed by pandaring2you** 2022-03-10 23:48 UTC
Labels: Peggy Team
